spring.application.name=groupsfund

spring.profiles.active=dev

spring.datasource.url=
spring.datasource.username= 
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.hibernate.ddl-auto=
spring.jpa.database-platform=


app.security.aes.secret-key=    
